#!/usr/bin/env bash
# phone-remote installer — bootstraps .env.production interactively.
#
# Generates a SESSION_SECRET, prompts for an admin username + password,
# hashes via bcrypt, and (optionally) captures Headscale config. Writes
# the resulting .env.production at mode 0600. Refuses to overwrite an
# existing file unless --force is passed.
#
# Usage:
#   ./infra/setup.sh                # interactive
#   ./infra/setup.sh --force        # overwrite existing .env.production
#
# Prerequisites: openssl, pnpm (workspace install must already have been
# run — `pnpm install` from the repo root).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${REPO_ROOT}/.env.production"
EXAMPLE="${REPO_ROOT}/infra/env.example"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    --help|-h)
      sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown flag: $arg" >&2
      exit 64
      ;;
  esac
done

die() { echo "error: $*" >&2; exit 1; }

require() {
  command -v "$1" >/dev/null 2>&1 || die "required tool '$1' not on PATH"
}

require openssl
require pnpm

if [[ ! -d "${REPO_ROOT}/node_modules" || ! -d "${REPO_ROOT}/apps/hub/node_modules" ]]; then
  die "pnpm install not run yet — run 'pnpm install' from ${REPO_ROOT} first"
fi

if [[ -e "$TARGET" && "$FORCE" -ne 1 ]]; then
  die ".env.production already exists at ${TARGET} (pass --force to overwrite)"
fi

# ---- session secret ---------------------------------------------------------
SESSION_SECRET="$(openssl rand -hex 32)"
[[ "${#SESSION_SECRET}" -eq 64 ]] || die "openssl produced a malformed secret"

# ---- admin username ---------------------------------------------------------
AUTH_USER=""
while [[ -z "$AUTH_USER" ]]; do
  read -r -p "Admin username: " AUTH_USER
  if [[ -z "$AUTH_USER" ]]; then
    echo "  (cannot be empty)"
    continue
  fi
  case "${AUTH_USER,,}" in
    admin|root|administrator|user|test)
      echo "  warning: '${AUTH_USER}' is a credential-stuffing magnet. Consider a less obvious name."
      read -r -p "  use '${AUTH_USER}' anyway? [y/N] " confirm
      [[ "${confirm,,}" == y* ]] || AUTH_USER=""
      ;;
  esac
done

# ---- password (twice, no echo, min length) ----------------------------------
MIN_LEN=12
PW=""
while true; do
  read -r -s -p "Admin password (min ${MIN_LEN} chars, no echo): " PW
  echo
  if [[ "${#PW}" -lt $MIN_LEN ]]; then
    echo "  (too short — got ${#PW}, need ${MIN_LEN}+)"
    continue
  fi
  read -r -s -p "Confirm password: " PW2
  echo
  if [[ "$PW" != "$PW2" ]]; then
    echo "  (passwords didn't match)"
    continue
  fi
  break
done
unset PW2

# Hash via the existing pnpm script. Capture only the last line of stdout to
# avoid pulling in pnpm progress chatter.
AUTH_PASSWORD_HASH="$(pnpm -F @phone-remote/hub --silent run hash-password "$PW" 2>/dev/null | tail -n 1)"
unset PW
[[ "$AUTH_PASSWORD_HASH" =~ ^\$2[aby]\$[0-9]+\$ ]] || die "bcrypt hash unexpected: ${AUTH_PASSWORD_HASH}"

# ---- optional headscale -----------------------------------------------------
echo
echo "Headscale (optional — leave blank to skip; tailnet provisioning will be disabled)"
read -r -p "  HEADSCALE_URL [empty to skip]: " HEADSCALE_URL
HEADSCALE_API_KEY=""
HEADSCALE_USER_ID=""
if [[ -n "$HEADSCALE_URL" ]]; then
  read -r -s -p "  HEADSCALE_API_KEY: " HEADSCALE_API_KEY
  echo
  read -r -p "  HEADSCALE_USER_ID [1]: " HEADSCALE_USER_ID
  HEADSCALE_USER_ID="${HEADSCALE_USER_ID:-1}"
fi

# ---- network bindings -------------------------------------------------------
read -r -p "Bind HOST [127.0.0.1]: " HOST
HOST="${HOST:-127.0.0.1}"
read -r -p "Bind PORT [4000]: " PORT
PORT="${PORT:-4000}"
read -r -p "TLS terminator in front (Caddy / Tailscale Serve)? sets COOKIE_SECURE=true [y/N]: " tls_yn
if [[ "${tls_yn,,}" == y* ]]; then
  COOKIE_SECURE=true
else
  COOKIE_SECURE=false
fi

# ---- write file -------------------------------------------------------------
umask 077
{
  printf '# Generated by infra/setup.sh on %s\n' "$(date -u +%FT%TZ)"
  printf '# DO NOT commit this file — it is gitignored.\n\n'
  printf 'HOST=%s\n' "$HOST"
  printf 'PORT=%s\n' "$PORT"
  printf 'COOKIE_SECURE=%s\n\n' "$COOKIE_SECURE"
  printf 'SESSION_SECRET=%s\n' "$SESSION_SECRET"
  printf 'AUTH_USER=%s\n' "$AUTH_USER"
  printf 'AUTH_PASSWORD_HASH=%s\n\n' "$AUTH_PASSWORD_HASH"
  if [[ -n "$HEADSCALE_URL" ]]; then
    printf 'HEADSCALE_URL=%s\n' "$HEADSCALE_URL"
    printf 'HEADSCALE_API_KEY=%s\n' "$HEADSCALE_API_KEY"
    printf 'HEADSCALE_USER_ID=%s\n\n' "$HEADSCALE_USER_ID"
  else
    printf '# HEADSCALE_URL=\n# HEADSCALE_API_KEY=\n# HEADSCALE_USER_ID=1\n\n'
  fi
  printf 'PROVISION_TAG=tag:phone\n'
  printf 'PROVISION_EXPIRY_SEC=3600\n\n'
  printf '# adb-server is started inside the container by ADB_AUTO_START=1.\n'
  printf 'ADB_AUTO_START=1\n'
  printf 'LOG_LEVEL=info\n'
} > "$TARGET"

chmod 600 "$TARGET"

# ---- create empty .env.local for hot-reload bind mount ----------------------
ENV_LOCAL="${REPO_ROOT}/.env.local"
if [[ ! -e "$ENV_LOCAL" ]]; then
  : > "$ENV_LOCAL"
  chmod 600 "$ENV_LOCAL"
fi

echo
echo "✓ Wrote ${TARGET} (mode 600)"
echo "  AUTH_USER=${AUTH_USER}"
echo "  SESSION_SECRET / AUTH_PASSWORD_HASH set (not echoed)"
[[ -n "$HEADSCALE_URL" ]] && echo "  Headscale: ${HEADSCALE_URL}"
echo
echo "Next:"
echo "  docker compose up -d --build      # or: pnpm -F @phone-remote/hub start"
echo "  Login at http://${HOST}:${PORT}/ as '${AUTH_USER}'"
